/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:cd0c2edfd73f8b9f7fc25a992ce86370:2adc14534ee3fc195bc7efe38741535d:2fb04318ffd01ef337ef66456d2b4e42$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string Adventurer-idle-2-00 = "adventurer-idle-2-00";
		public const string Adventurer-idle-2-01 = "adventurer-idle-2-01";
		public const string Adventurer-idle-2-02 = "adventurer-idle-2-02";
		public const string Adventurer-idle-2-03 = "adventurer-idle-2-03";
		public const string Adventurer-jump-00 = "adventurer-jump-00";
		public const string Adventurer-jump-01 = "adventurer-jump-01";
		public const string Adventurer-jump-02 = "adventurer-jump-02";
		public const string Adventurer-jump-03 = "adventurer-jump-03";
		public const string Adventurer-run-00 = "adventurer-run-00";
		public const string Adventurer-run-01 = "adventurer-run-01";
		public const string Adventurer-run-02 = "adventurer-run-02";
		public const string Adventurer-run-03 = "adventurer-run-03";
		public const string Adventurer-run-04 = "adventurer-run-04";
		public const string Adventurer-run-05 = "adventurer-run-05";
		public const string Adventurer-slide-00 = "adventurer-slide-00";
		public const string Adventurer-slide-01 = "adventurer-slide-01";
		public const string Adventurer-smrslt-00 = "adventurer-smrslt-00";
		public const string Adventurer-smrslt-01 = "adventurer-smrslt-01";
		public const string Adventurer-smrslt-02 = "adventurer-smrslt-02";
		public const string Adventurer-smrslt-03 = "adventurer-smrslt-03";
		public const string Adventurer-stand-00 = "adventurer-stand-00";
		public const string Adventurer-stand-01 = "adventurer-stand-01";
		public const string Adventurer-stand-02 = "adventurer-stand-02";
	}
}